# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
beps <- function(inp_dir) {
    .Call(`_rBEPS_beps`, inp_dir)
}

