# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculating cosZ
#' @param j hour of day
#' @export
s_coszs_R <- function(jday, j, lat, lon) {
    .Call(`_rBEPS_s_coszs_R`, jday, j, lat, lon)
}

#' @export
readcoef_R <- function(lc, stxt) {
    .Call(`_rBEPS_readcoef_R`, lc, stxt)
}

#' @export
beps <- function(inp_dir) {
    .Call(`_rBEPS_beps`, inp_dir)
}

