# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculating cosZ
#' @param j hour of day
#' @export
#' @examples
#' S_coszs(1, 1, 15, 120)
S_coszs <- function(jday, j, lat, lon) {
    .Call(`_rBEPS_S_coszs`, jday, j, lat, lon)
}

#' Real soil coefficients
#'
#' @param lc    land cover type
#'               1-ENF 2-DNF 6-DBF 9-EBF 13-Shrub 40-C4 Plants default:Others
#' @param stxt  soil texture, 1-11
#' @export
#' @examples
#' Readcoef(1, 1)
Readcoef <- function(lc, stxt) {
    .Call(`_rBEPS_Readcoef`, lc, stxt)
}

#' @export
beps <- function(inp_dir) {
    .Call(`_rBEPS_beps`, inp_dir)
}

